### ISSUE TITLE
docs: `starter.yaml` example should not trigger deployment on every push

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/gl-autodevops-minimal-port#3]
the currently recommended `starter.yaml` in the readme triggers deployment on every push to any branch (see https://github.com/acdh-oeaw/gl-autodevops-minimal-port#usage).

since this code is copy-pasted into many of our repositories, i think a better default would be something like this:

```yaml
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
```
